name: chatkuy
version: 1.1.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  firebase_core: 1.10.5
  firebase_auth: 3.3.3
  google_sign_in: 5.2.1
  lottie: 1.2.1
  introduction_screen: 2.1.0
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.0.8
  get_storage: 2.0.3
  cloud_firestore: 3.1.4
  intl: 0.17.0
  image_picker: 0.8.4+4
  firebase_storage: 10.2.4
  google_fonts: 2.3.1
  flutter_launcher_icons: 0.9.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/favicon.png"

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
    - assets/image/
  uses-material-design: true

